{
 "title": "Falco",
 "description": "Grafana dashboard for Falco output events",
 "tags": [
  "Security",
  "Runtime"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "priority",
    "label": "Priority",
    "query": "EMERGENCY,ALERT,CRITICAL,ERROR,WARNING,NOTICE,INFORMATIONAL,DEBUG"
   },
   { "name": "top", "label": "Top", "query": "5,10,20,50" },
   { "name": "searchpattern", "label": "Search Pattern", "query": "shadow" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Events ($priority)",
   "type": "stat",
   "description": "Total falco events recorded from ${__from:date:YYYY-MM-DD HH:mm}\n to ${__to:date:YYYY-MM-DD HH:mm}.",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({juju_charm=\"falco\"} | json | priority=~\"(?i)$priority\"[$__range]))"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "piechart",
   "description": "The distribution of sources of falco logs.",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (source) (count_over_time({juju_charm=\"falco\"} | json | priority=~\"(?i)$priority\"[$__range]))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Priorities",
   "type": "piechart",
   "description": "The distribution of priorities of falco logs.",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (priority) (count_over_time({juju_charm=\"falco\"} | json | priority=~\"(?i)$priority\"[$__range]))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Rules",
   "type": "piechart",
   "description": "The distribution of triggered rules.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rule) (count_over_time({juju_charm=\"falco\"} | json | priority=~\"(?i)$priority\"[$__range]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Events rate per minute",
   "type": "timeseries",
   "description": "The rate of falco event logs per minute",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (priority) (count_over_time({juju_charm=\"falco\"} | json | priority=~\"(?i)$priority\"[1m]))",
     "legendFormat": "{{priority}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Top $top pods",
   "type": "table",
   "description": "The top $top pods that violate falco rules.",
   "gridPos": { "h": 12, "w": 7, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "sum by (output_fields_k8s_ns_name, output_fields_k8s_pod_name) (\r\n  count_over_time({juju_charm=\"falco\"} | json | priority=~\"(?i)$priority\",priority!=\"Debug\"\r\n    | logfmt | __error__ = \"\" \r\n    | container_id!=\"host\", k8s_pod_name!=\"<NA>\"[$__range]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Top $top units",
   "type": "table",
   "description": "The top $top units that violate falco rules.",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 10 },
   "targets": [
    {
     "expr": "sum by (output_fields_juju_model, output_fields_juju_unit) (\r\n  count_over_time({juju_charm=\"falco\"} | json | priority=~\"(?i)$priority\",priority!=\"Debug\"\r\n    | logfmt | __error__ = \"\" \r\n    | container_id=\"host\"[$__range]\r\n  )\r\n)"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{juju_charm=\"falco\"} | json | priority=~\"(?i)$priority\" |~ \"(?i)$searchpattern\"\n| line_format `{{ alignLeft 11 (upper .priority) }} | {{__line__ }}`"
    }
   ]
  }
 ]
}